### PR TITLE
Stop using hardcoded list of devices

### PR DESCRIPTION
**Pull request by dobey**
Determines which image to use for anbox based on kernel config and
architecture. This allows anbox to be set up on devices which are
still ports in progress, but where anbox support has been enabled by
the porter; and also paves the way for enabling anbox on mainline devices.

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Until generic and arm64 Anbox images are released, this should not be merged.

**Comment by mariogrip** [comment]
> Until generic and arm64 Anbox images are released, this should not be merged.

agree, also ci should do the building of these images. they are really old at this point

**Comment by dobey** [comment]
> Until generic and arm64 Anbox images are released, this should not be merged.

I've just pushed a change to always use armhf images until we can get additional images built for arm64 and amd64. This should let us at least ship this, and allow everyone to just do `anbox-tool install` on their phones/tablets anyway, assuming kernel support exists.

**Review by UniversalSuperBox — APPROVED** [review]
Yes, improving the experience even a little seems sound.

**Comment by luksus42** [comment]
Works for arm64 Halium 9 device: FP3. Dev-Channel (2021-05-04).

Is it expected, that on Halium 9 the Anbox Android version is 7.1.1?

**Comment by dobey** [comment]
> Is it expected, that on Halium 9 the Anbox Android version is 7.1.1?

Yes. The Anbox image isn't the same as the minimal Android used to boot with on devices (such as 5.1 on Nexus 5).

**Pull request merged**
